# Generated by Django 4.2.4 on 2023-08-18 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0006_reservation_dtae_reservation_end_d_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='dtae',
            new_name='date',
        ),
    ]
