# Generated by Django 4.2.4 on 2023-08-18 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0007_rename_dtae_reservation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
