# Generated by Django 4.2.4 on 2023-08-18 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_latitude', models.CharField(max_length=50)),
                ('start_longitude', models.CharField(max_length=50)),
                ('end_latitude', models.CharField(max_length=50)),
                ('end_longitude', models.CharField(max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
