# Generated by Django 4.2.4 on 2023-08-19 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_proplem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='proplem',
            new_name='problem',
        ),
    ]
